/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author dhara
 */
public class ad extends javax.swing.JFrame {

    /**
     * Creates new form ad
     */
    public ad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("jdbc:oracle:thin:@localhost:1521:orclPU").createEntityManager();
        bikes_1Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM Bikes_1 b");
        bikes_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : bikes_1Query.getResultList();
        booksbikeQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM Booksbike b");
        booksbikeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : booksbikeQuery.getResultList();
        custQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cust c");
        custList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : custQuery.getResultList();
        delHistoryQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DelHistory d");
        delHistoryList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : delHistoryQuery.getResultList();
        cancelHistoryQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM CancelHistory c");
        cancelHistoryList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cancelHistoryQuery.getResultList();
        delHistoryQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DelHistory d");
        delHistoryList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : delHistoryQuery1.getResultList();
        delHistoryQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DelHistory d");
        delHistoryList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : delHistoryQuery2.getResultList();
        delHistoryQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DelHistory d");
        delHistoryList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : delHistoryQuery3.getResultList();
        delHistoryQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DelHistory d");
        delHistoryList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : delHistoryQuery4.getResultList();
        delHistoryQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DelHistory d");
        delHistoryList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : delHistoryQuery5.getResultList();
        delHistoryQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DelHistory d");
        delHistoryList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : delHistoryQuery6.getResultList();
        delHistoryQuery7 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DelHistory d");
        delHistoryList7 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : delHistoryQuery7.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(null);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel7.setText("BIKE ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(105, 82, 110, 22);

        jComboBox1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "duke125", "duke200", "duke390", "rc125", "rc200", "rc390" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(288, 78, 260, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("CID");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(105, 164, 38, 17);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(jTextField2);
        jTextField2.setBounds(288, 161, 260, 23);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("DETAILS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(366, 230, 91, 25);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("NAME");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(105, 330, 39, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("CONTACT");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(105, 425, 66, 17);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(jTextField3);
        jTextField3.setBounds(288, 327, 260, 23);

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(jTextField4);
        jTextField4.setBounds(288, 422, 260, 23);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("AREA");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(105, 517, 38, 17);

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel3.add(jTextField5);
        jTextField5.setBounds(288, 514, 260, 23);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("SHOW");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(675, 80, 75, 25);

        jTabbedPane1.addTab("BOOKING REPORT", jPanel3);

        jPanel1.setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, booksbikeList, jTable2);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cid}"));
        columnBinding.setColumnName("Cid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bid}"));
        columnBinding.setColumnName("Bid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${testDrive}"));
        columnBinding.setColumnName("Test Drive");
        columnBinding.setColumnClass(Short.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(95, 51, 923, 330);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("1- TESTDRIVE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(493, 436, 150, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("0- DIRECT BOOKING");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(493, 486, 180, 17);

        jTabbedPane1.addTab("BOOKING TABLE", jPanel1);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cancelHistoryList, jTable5);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cid}"));
        columnBinding.setColumnName("Cid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bid}"));
        columnBinding.setColumnName("Bid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bookingdate}"));
        columnBinding.setColumnName("Bookingdate");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${reason}"));
        columnBinding.setColumnName("Reason");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${action}"));
        columnBinding.setColumnName("Action");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CANCELATION REPORT", jPanel6);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, bikes_1List, jTable1);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bid}"));
        columnBinding.setColumnName("Bid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${price}"));
        columnBinding.setColumnName("Price");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${specification}"));
        columnBinding.setColumnName("Specification");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${availablity}"));
        columnBinding.setColumnName("Availablity");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${modelType}"));
        columnBinding.setColumnName("Model Type");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 307, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VIEW BIKES", jPanel2);

        jPanel4.setLayout(null);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, custList, jTable4);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cid}"));
        columnBinding.setColumnName("Cid");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${contact}"));
        columnBinding.setColumnName("Contact");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${location}"));
        columnBinding.setColumnName("Location");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane4.setViewportView(jTable4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(12, 161, 985, 418);

        jLabel2.setText("CID");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(103, 25, 34, 16);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(180, 20, 210, 30);

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(454, 21, 75, 25);

        jLabel13.setText("REASON");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(100, 80, 70, 16);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(180, 70, 210, 30);

        jTabbedPane1.addTab("DELETE CUSTOMER", jPanel4);

        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("REFRESH");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel5.add(jLabel3);
        jLabel3.setBounds(381, 9, 70, 23);

        jButton2.setText("logout");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(468, 504, 80, 23);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("ENTER CID TO ADD USER AGAIN:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(103, 358, 223, 17);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel5.add(jTextField6);
        jTextField6.setBounds(468, 355, 234, 23);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("ADD AGAIN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(807, 354, 111, 25);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jPanel5.add(jScrollPane6);
        jScrollPane6.setBounds(0, 50, 1100, 220);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("SHOW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(500, 10, 90, 31);

        jTabbedPane1.addTab("VIEW DELETED CUSTOMER", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ADMINISTRATOR PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 25, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myproject/BG1.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -10, -1, 1490));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Happiness15");
            String sql="DELETE FROM cust where cid='"+ jTextField1.getText() +"' ";
            PreparedStatement ps1=conn.prepareStatement(sql);
            ResultSet rs1=ps1.executeQuery();            
                   if(rs1.next()){
                    JOptionPane.showMessageDialog(null,"DELETE SUCCESSFULL"); 
                   }
                   else 
                {
		JOptionPane.showMessageDialog(null,"INVALID");
                conn.close();
                rs1.close();}
        }catch(Exception e1){System.out.println(e1);       

           // System.out.println("deleted sucessfully");
            
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        ad a= new ad();
        this.setVisible(false);
        a.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        adminlogin h=new adminlogin();
        this.setVisible(false);
        h.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Happiness15");
            String sql = "SELECT name,contact,location FROM cust where cid = '"+jTextField2.getText()+"' ";
            PreparedStatement ps1=conn.prepareStatement(sql);
            ResultSet rs1=ps1.executeQuery();            
            if(rs1.next()) 
                        {
                            String name =rs1.getString("name");
                            String contact =rs1.getString("contact");
                            String location =rs1.getString("location");
                            
                            jTextField3.setText(name);
                            jTextField4.setText(contact);
                            jTextField5.setText(location);
                        }

                 
            }catch(Exception e1){System.out.println(e1);   
            }
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         //Object duke390 = null;
        // TODO add your handling code here:
       // DefaultListModel<String> jList1 = new DefaultListModel();
        try{
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Happiness15");
            String sql = "select cid FROM booksbike where bid = '"+jComboBox1.getSelectedItem()+"' ";
           // System.out.println("Passed sql string");
            PreparedStatement ps1=conn.prepareStatement(sql);
            ResultSet rs1=ps1.executeQuery();    
           // System.out.println("Result string fetched");
            if(rs1.next()) 
                        {
                            String cid =rs1.getString("cid");
                            //System.out.println("Printing sql string");
                            jTextField2.setText(cid);
                            //System.out.println("Printed sql string");
                        }

                 
            }catch(Exception e1){System.out.println(e1);   
            }
        /*if(jComboBox1.getSelectedItem().equals(duke390))
        {
            jTextField1.setText("sriram1");
        }*/
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        try{
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Happiness15");
            String sql="DELETE FROM DEL_HISTORY where cid='"+ jTextField6.getText() +"' ";
            PreparedStatement ps1=conn.prepareStatement(sql);
            ResultSet rs1=ps1.executeQuery();            
                   if(rs1.next()){
                    JOptionPane.showMessageDialog(null,"ADDED SUCCESSFULL"); 
                   }
                   else 
                {
		JOptionPane.showMessageDialog(null,"INVALID");
                conn.close();
                rs1.close();}
        }catch(SQLException | HeadlessException e1){System.out.println(e1); }   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try{
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Happiness15");
               String sql = "select * FROM del_history ";
                PreparedStatement ps1=conn.prepareStatement(sql);
                ResultSet rs1=ps1.executeQuery(); 
                jTable6.setModel(DbUtils.resultSetToTableModel(rs1));
                }catch(SQLException | HeadlessException e1){System.out.println(e1); }  
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<myproject.Bikes_1> bikes_1List;
    private javax.persistence.Query bikes_1Query;
    private java.util.List<myproject.Booksbike> booksbikeList;
    private javax.persistence.Query booksbikeQuery;
    private java.util.List<myproject.CancelHistory> cancelHistoryList;
    private javax.persistence.Query cancelHistoryQuery;
    private java.util.List<myproject.Cust> custList;
    private javax.persistence.Query custQuery;
    private java.util.List<myproject.DelHistory> delHistoryList;
    private java.util.List<myproject.DelHistory> delHistoryList1;
    private java.util.List<myproject.DelHistory> delHistoryList2;
    private java.util.List<myproject.DelHistory> delHistoryList3;
    private java.util.List<myproject.DelHistory> delHistoryList4;
    private java.util.List<myproject.DelHistory> delHistoryList5;
    private java.util.List<myproject.DelHistory> delHistoryList6;
    private java.util.List<myproject.DelHistory> delHistoryList7;
    private javax.persistence.Query delHistoryQuery;
    private javax.persistence.Query delHistoryQuery1;
    private javax.persistence.Query delHistoryQuery2;
    private javax.persistence.Query delHistoryQuery3;
    private javax.persistence.Query delHistoryQuery4;
    private javax.persistence.Query delHistoryQuery5;
    private javax.persistence.Query delHistoryQuery6;
    private javax.persistence.Query delHistoryQuery7;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
